import Head from 'next/head'
import React, { useEffect, useMemo, useRef, useState } from 'react'
import Quiz from '../components/Quiz'
import Image from 'next/image'
import style from '../styles/Main.module.css'
import logo from '../assets/kbc.png'
import Message from '../components/Message'
export default function Home() {
 const [queNo,setQuNo]=useState(1)
 const [timeStop,setTimeStop]=useState(false)
  const [userName,setUserName]=useState(null)
  const [amountEraned,setAmountEarned]=useState('0')
  const [fiftyFity,setFity]=useState(false)

  
  const inputRef=useRef(null)
  const money= useMemo(()=>
  ["5,000","10,000","20,000","40,000","80,000","1,60,000","3,20,000","6,40,000","12,80,000","25,00,000","50,00,000","1 Crore","3 Crore"," 7 Crore"]
 ,[])
  useEffect(()=>{
    queNo>1 && setAmountEarned(money.find((amt,i)=>(money.length-i)-1))
  },[money,queNo])

  const selectFiftyFity=()=>{
  setFity(true)
  }
  return (

    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <Message amount={amountEraned} show={timeStop} setShow={setTimeStop}/>
      <main className={style.main}>
        {
          userName?(
             <>
              <div className={style.questions}>
           <div className={style.topSec}>
            <Image src={logo} width={100} height={110}/>
            <div className={style.lifeLine}>
              <p>Life lines: </p>
              {fiftyFity?(<div className={`${style.icon} ${style.iconDis}`}>
                 50/50
                 <div className={style.line}></div>
              </div>):(<div className={style.icon} onClick={selectFiftyFity}>
                50/50
              </div>)}
              
              <div className={style.icon}>
                <Image src="https://cdn-icons-png.flaticon.com/512/6386/6386588.png" alt="" width={30} height={30}/>

              </div>
            </div>
           </div>
            <Quiz setTimeStop={setTimeStop} setQuNo={setQuNo} queNo={queNo} fiftyFity={fiftyFity} setFity={setFity}/>
         </div>
         <div className={style.money}>
           <ul className={style.moneyList}>
             {
               money.slice(0).reverse().map((amount,i)=>(
                 <React.Fragment key={i}>
                <li key={i} className={queNo===money.length-i&& style.active}> 
                  <span>{i+1}</span> <span>₹ {amount}</span>
                  </li>
                  </React.Fragment>
               ))
             }
            
            
           </ul>
         </div>
             </>
          ):(
            <div className={style.inputArea}>
              <input ref={inputRef} type="text" placeholder='Enter Your Name' />
              <button onClick={()=>setUserName(inputRef.current.value)}>Start</button>
            </div>
          )
        }
        
      </main>
    </div>
  )
}
